# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Genshin Intact' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Genshin Intact
  
  # Infrastructure
  pod 'PromiseKit', '~> 8'
  
  # Reactive frameworks
  pod 'RxSwift', '6.6.0'
  pod 'RxCocoa', '6.6.0'

  target 'Genshin IntactTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Genshin IntactUITests' do
    # Pods for testing
  end

end
